@StaticRustLauncherBackend_HostAddress = http://localhost:5208

### Получение новостей
GET {{StaticRustLauncherBackend_HostAddress}}/api/news
Accept: application/json

###

### Получение хостингов
GET {{StaticRustLauncherBackend_HostAddress}}/api/hostings
Accept: application/json

###

### Получение серверов
GET {{StaticRustLauncherBackend_HostAddress}}/api/servers
Accept: application/json

###

### Получение статистики
GET {{StaticRustLauncherBackend_HostAddress}}/api/statistics
Accept: application/json

###

### Получение информации о версиях
GET {{StaticRustLauncherBackend_HostAddress}}/api/version
Accept: application/json

###

### Получение версии клиента
GET {{StaticRustLauncherBackend_HostAddress}}/api/version/client
Accept: application/json

###
